#!/bin/bash
# calling this from kanshi config DOES NOT WORK 2024-12-23
ext_src={1:-"DP-1"}

swaymsg workspace 1 output "eDP-1"
swaymsg workspace 2 output "eDP-1"
swaymsg workspace 3 output "eDP-1"
swaymsg workspace 4 output "eDP-1"
swaymsg workspace 5 output "eDP-1"

swaymsg workspace 6 output  "$ext_src"
swaymsg workspace 7 output  "$ext_src"
swaymsg workspace 8 output  "$ext_src"
swaymsg workspace 9 output  "$ext_src"
swaymsg workspace 10 output "$ext_src"
swaymsg workspace 11 output "$ext_src"
swaymsg workspace 12 output "$ext_src"
swaymsg workspace 13 output "$ext_src"

swaymsg workspace 1
swaymsg workspace 6
