import = ["~/.config/alacritty/themes/everforest_dark.toml"]

[colors]
draw_bold_text_with_bright_colors = false

[font.normal]
family = "MesloLGS NF"

[[keyboard.bindings]]
chars = "\u001B[105;5u"
key = "I"
mods = "Control"
