
[colors]
draw_bold_text_with_bright_colors = false

[font.normal]
family = "MesloLGS NF"

[[keyboard.bindings]]
key = "I"
mods = "Control"
chars = "\u001B[105;5u"

[general]
import = ["~/.config/alacritty/themes/everforest_dark.toml"]

